# Generated by Django 5.2.3 on 2025-08-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('preço', models.IntegerField(max_length=20)),
                ('estoque', models.IntegerField(max_length=10)),
            ],
        ),
    ]
