# Generated by Django 5.2.3 on 2025-08-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preço',
            field=models.IntegerField(),
        ),
    ]
