# Generated by Django 5.2.3 on 2025-08-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_produto_imagem_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preço',
            new_name='preco',
        ),
    ]
